{
 "title": "KPI, Method, Response",
 "tags": [ "sip" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "tn", "label": "interface_name", "query": "heplify_method_response" }
  ]
 },
 "panels": [
  {
   "title": "SIP KPI's",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(heplify_method_response{target_name=\"$tn\",method=\"INVITE\",response=\"200\"}[5m])) * 100) / \n(sum(increase(heplify_method_response{target_name=\"$tn\",method=\"INVITE\",response=\"INVITE\"}[5m])) - \n(sum(increase(heplify_method_response{target_name=\"$tn\",method=\"INVITE\",response=~\"3.*|401|407\"}[5m])) or sum(up) * 0)) <=100",
     "legendFormat": "SER (ASR)"
    },
    {
     "expr": "(sum(increase(heplify_method_response{target_name=\"$tn\",method=\"INVITE\",response=~\"200|480|486|600|603\"}[5m])) * 100) / \n(sum(increase(heplify_method_response{target_name=\"$tn\",method=\"INVITE\",response=\"INVITE\"}[5m])) - \n(sum(increase(heplify_method_response{target_name=\"$tn\",method=\"INVITE\",response=~\"3.*|401|407\"}[5m])) or sum(up) * 0)) <=100",
     "legendFormat": "SEER (NER)"
    },
    {
     "expr": "(sum(increase(heplify_method_response{target_name=\"$tn\",method=\"BYE\", response=\"200\"}[5m])) * 100) / \n(sum(increase(heplify_method_response{target_name=\"$tn\",method=\"INVITE\",response=\"INVITE\"}[5m]))) <=100",
     "legendFormat": "SCR"
    }
   ]
  },
  {
   "title": "SIP KPI's",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "((sum(increase(heplify_method_response{target_name=\"$tn\",method=\"REGISTER\",response=~\"4.*|5.*|6.*\"}[5m])) - \nsum(increase(heplify_method_response{target_name=\"$tn\",method=\"REGISTER\", response=~\"401|402|407\"}[5m]))) * 100) / \n(sum(increase(heplify_method_response{target_name=\"$tn\",method=\"REGISTER\",response=\"REGISTER\"}[5m])))<=100",
     "legendFormat": "IRA"
    },
    {
     "expr": "(sum(increase(heplify_method_response{target_name=\"$tn\",method=\"INVITE\", response=~\"408|500|503|504\"}[5m])) * 100) / \n(sum(increase(heplify_method_response{target_name=\"$tn\",method=\"INVITE\",response=\"INVITE\"}[5m])))<=100",
     "legendFormat": "ISA"
    },
    {
     "expr": "(sum(increase(heplify_method_response{target_name=\"$tn\",method=\"INVITE\", response=~\"500|503|504\"}[5m])) * 100) / \n(sum(increase(heplify_method_response{target_name=\"$tn\",method=\"INVITE\",response=\"INVITE\"}[5m])))<=100",
     "legendFormat": "SDR"
    }
   ]
  },
  {
   "title": "Calls per second & Call attempts per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(heplify_method_response{target_name=\"$tn\",method=\"INVITE\",response=\"200\"}[2m])",
     "legendFormat": "CPS"
    },
    {
     "expr": "rate(heplify_method_response{target_name=\"$tn\",method=\"INVITE\",response=\"INVITE\"}[2m])",
     "legendFormat": "CAPS"
    }
   ]
  },
  {
   "title": "Concurrent Sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(heplify_method_response{target_name=\"$tn\",method=\"INVITE\",response=\"200\"}[5m]))) / \n(sum(increase(heplify_method_response{target_name=\"$tn\",method=\"INVITE\",response=\"INVITE\"}[5m])) - \n(sum(increase(heplify_method_response{target_name=\"$tn\",method=\"INVITE\",response=~\"3.*|401|407\"}[5m])) or sum(up) * 0)) * \n160 * sum(rate(heplify_method_response{target_name=\"$tn\",method=\"INVITE\",response=\"INVITE\"}[5m]))",
     "legendFormat": "CCC"
    }
   ]
  },
  {
   "title": "Register per second & Register attempts per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(heplify_method_response{target_name=\"$tn\",method=\"REGISTER\",response=\"200\"}[2m])",
     "legendFormat": "RPS"
    },
    {
     "expr": "rate(heplify_method_response{target_name=\"$tn\",method=\"REGISTER\",response=\"REGISTER\"}[2m])",
     "legendFormat": "RAPS"
    }
   ]
  },
  {
   "title": "Register with 401",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(heplify_method_response{target_name=\"$tn\",method=\"REGISTER\",response=\"401\"}[2m])",
     "legendFormat": "{{ method }} {{ response }}"
    }
   ]
  },
  {
   "title": "403|404 errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(heplify_method_response{target_name=\"$tn\",response=~\"403|404\"}[1m])",
     "legendFormat": "{{ method }} {{ response }}"
    }
   ]
  },
  {
   "title": "4.* invites without (403|404|407|486|487)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(heplify_method_response{target_name=\"$tn\",method=\"INVITE\",response=~\"4.*\",response!~\"403|404|407|486|487\"}[2m])",
     "legendFormat": "{{ method }} {{ response }}"
    }
   ]
  },
  {
   "title": "5.* server errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(heplify_method_response{target_name=\"$tn\",response=~\"50.*\"}[1m])",
     "legendFormat": "{{ method }} {{ response }}"
    }
   ]
  }
 ]
}