{
 "title": "SIP Overview",
 "tags": [ "sip" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "tn", "label": "interface_name", "query": "heplify_method_response" }
  ]
 },
 "panels": [
  {
   "title": "KPI's",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(heplify_method_response{target_name=~\"$tn\", method=\"INVITE\", response=\"200\"}[5m])) * 100) / \n(sum(increase(heplify_method_response{target_name=~\"$tn\", method=\"INVITE\", response=\"INVITE\"}[5m])) - \n(sum(increase(heplify_method_response{target_name=~\"$tn\", method=\"INVITE\", response=~\"3.*|401|407\"}[5m])) or sum(up) * 0)) <=100",
     "legendFormat": "ASR"
    },
    {
     "expr": "(sum(increase(heplify_method_response{target_name=~\"$tn\", method=\"INVITE\", response=~\"200|480|486|600|603\"}[5m])) * 100) / \n(sum(increase(heplify_method_response{target_name=~\"$tn\", method=\"INVITE\", response=\"INVITE\"}[5m])) - \n(sum(increase(heplify_method_response{target_name=~\"$tn\", method=\"INVITE\", response=~\"3.*|401|407\"}[5m])) or sum(up) * 0)) <=100",
     "legendFormat": "NER"
    },
    {
     "expr": "((sum(increase(heplify_method_response{target_name=~\"$tn\", method=\"REGISTER\", response=~\"4.*|5.*|6.*\"}[5m])) - \nsum(increase(heplify_method_response{target_name=~\"$tn\", method=\"REGISTER\", response=~\"401|402|407\"}[5m]))) * 100) / \n(sum(increase(heplify_method_response{target_name=~\"$tn\", method=\"REGISTER\", response=\"REGISTER\"}[5m]))) <=100",
     "legendFormat": "IRA"
    }
   ]
  },
  {
   "title": "Successful Calls & Register per second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(heplify_method_response{target_name=~\"$tn\", method=\"INVITE\", response=\"200\"}[1m])",
     "legendFormat": "CPS"
    },
    {
     "expr": "rate(heplify_method_response{target_name=~\"$tn\", method=\"REGISTER\", response=\"200\"}[1m])",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "Invite & Register 403 | 404 | 408 | 480 | 482",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(heplify_method_response{target_name=~\"$tn\", method=~\"INVITE|REGISTER\" ,response=~\"403|404|408|480|482\"}[2m])",
     "legendFormat": "{{ method }} {{ response }}"
    }
   ]
  },
  {
   "title": "Invite & Register 50.*",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(heplify_method_response{target_name=~\"$tn\",method=~\"INVITE|REGISTER\", response=~\"50.*\"}[2m])",
     "legendFormat": "{{ method }} {{ response }}"
    }
   ]
  }
 ]
}